# Generated by Django 3.2 on 2021-05-05 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210505_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='my_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
