# Generated by Django 3.2 on 2021-05-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210505_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_biddings', to=settings.AUTH_USER_MODEL),
        ),
    ]
