# Generated by Django 3.2 on 2021-05-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
