# Generated by Django 3.2 on 2021-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listings_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
