# Generated by Django 3.2 on 2021-05-18 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210518_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
