# Generated by Django 3.2 on 2021-05-25 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comments_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
